<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var  $block \Magento\Shipping\Block\Items */ ?>
<?php  $_order = $block->getOrder() ?>

<?php 
$_magb_helper = $this->helper('ITM\MagB1\Helper\Data');
$type ="sales_shipment";
$customer_id = $_order->getCustomerId();
?>

<div class="actions-toolbar">
    <?php if ($_order->getTracksCollection()->count()) : ?>
        <?= $block->getChildHtml('track-all-link') ?>
    <?php endif; ?>
    <a href="<?= /* @escapeNotVerified */ $block->getPrintAllShipmentsUrl($_order) ?>"
       onclick="this.target='_blank'"
       class="action print">
        <span><?= /* @escapeNotVerified */ __('Print All Shipments') ?></span>
    </a>
</div>
<?php foreach ($_order->getShipmentsCollection() as $_shipment): ?>

<?php $files = $_magb_helper->getShipmentFiles($customer_id, $_shipment->getIncrementId());?>

<div class="order-title">
    <strong><?= /* @escapeNotVerified */ __('Shipment #') ?><?= /* @escapeNotVerified */ $_shipment->getIncrementId() ?></strong>
    <a href="<?= /* @escapeNotVerified */ $block->getPrintShipmentUrl($_shipment) ?>"
       onclick="this.target='_blank'"
       class="action print">
        <span><?= /* @escapeNotVerified */ __('Print Shipment') ?></span>
    </a>
    <div style="height: 30px;">
     <span style="float:right;margin-left:20px;">
     <?php   if( count($files)): ?>
     	<ul style=" list-style-type: none;padding:0;margin:0">
    	   	<?php foreach ($files as $file): ?>
       		 <?php 
       		 $file_info = pathinfo ($file["path"]);
       		 $ext =  $file_info['extension'];
       		 ?>
       		 <li style="text-align: left;">
       		 <a target="_blank" href="<?php echo $this->getUrl('magb1/download/index',["type"=>$type,"id" =>$file["entity_id"]]); ?>">
       		 <img width=30 src="<?php echo $block->getViewFileUrl('ITM_MagB1::images/'.$ext.'.png'); ?>" title="<?php echo $file["path"]?> " alt="<?php echo $file["path"]?> " />
       		 <?php //echo $file["path"]?> 
       		 </a>
       		</li>
       		<?php endforeach; ?>
   		</ul>
     <?php endif; ?>
    </span>
    </div>
    
    <a href="#"
       data-mage-init='{"popupWindow": {"windowURL":"<?= /* @escapeNotVerified */ $this->helper('Magento\Shipping\Helper\Data')->getTrackingPopupUrlBySalesModel($_shipment) ?>","windowName":"trackshipment","width":800,"height":600,"top":0,"left":0,"resizable":1,"scrollbars":1}}'
       title="<?= /* @escapeNotVerified */ __('Track this shipment') ?>"
       class="action track">
        <span><?= /* @escapeNotVerified */ __('Track this shipment') ?></span>
    </a>
</div>
<?php $tracks = $_shipment->getTracksCollection(); ?>
<?php  if ($tracks->count()): ?>
    <dl class="order-tracking" id="my-tracking-table-<?= /* @escapeNotVerified */ $_shipment->getId() ?>">
        <dt class="tracking-title">
            <?= /* @escapeNotVerified */ __('Tracking Number(s):') ?>
        </dt>
        <dd class="tracking-content">
            <?php
            $i = 1;
            $_size = $tracks->count();
            foreach ($tracks as $track): ?>
                <?php if ($track->isCustom()): ?><?= $block->escapeHtml($track->getNumber()) ?><?php else: ?><a
                    href="#"
                    data-mage-init='{"popupWindow": {"windowURL":"<?= /* @escapeNotVerified */ $this->helper('Magento\Shipping\Helper\Data')->getTrackingPopupUrlBySalesModel($track) ?>","windowName":"trackorder","width":800,"height":600,"left":0,"top":0,"resizable":1,"scrollbars":1}}'
                    class="action track"><span><?= $block->escapeHtml($track->getNumber()) ?></span>
                    </a><?php endif; ?><?php if ($i != $_size): ?>, <?php endif; ?>
                <?php $i++;
            endforeach; ?>
        </dd>
    </dl>
<?php  endif; ?>
<div class="table-wrapper order-items-shipment">
    <table class="data table table-order-items shipment" id="my-shipment-table-<?= /* @escapeNotVerified */ $_shipment->getId() ?>">
        <caption class="table-caption"><?= /* @escapeNotVerified */ __('Items Shipped') ?></caption>
        <thead>
            <tr>
                <th class="col name"><?= /* @escapeNotVerified */ __('Product Name') ?></th>
                <th class="col sku"><?= /* @escapeNotVerified */ __('SKU') ?></th>
                <th class="col qty"><?= /* @escapeNotVerified */ __('Qty Shipped') ?></th>
            </tr>
        </thead>
        <?php $_items = $_shipment->getAllItems(); ?>
        <?php $_count = count($_items) ?>
        <?php foreach ($_items as $_item): ?>
        <?php if ($_item->getOrderItem()->getParentItem()) {
    continue;
} ?>
        <tbody>
            <?= $block->getItemHtml($_item) ?>
        </tbody>
        <?php endforeach; ?>
    </table>
</div>
<?= $block->getCommentsHtml($_shipment) ?>
<?php endforeach; ?>
